# docker-compose.python.yml
version: '3.8'

services:
  ai_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - chat_network
networks:
  chat_network:
    external: true